# TODO
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-redis
  name: service-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: deployment-redis
  type: ClusterIP
