version: '3.1'
services:

  redis:
    image: "redis:4"
    container_name: cache
    ports:
      - 6379:6379

  backend_container:
    build: ./backend
    environment:
      - REDIS_DNS=redis://cache
    ports:
      - 9000:9000
    depends_on: [redis]

  frontend_container:
    build: ./frontend
    ports:
      - 8080:8080
    depends_on: [backend_container]
