# TODO
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-redis
  name: deployment-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-redis
  template:
    metadata:
      labels:
        app: deployment-redis
    spec:
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: pvc-redis
      containers:
      - image: redis:alpine
        name: redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
        - mountPath: "/data"
          name: redis-volume
