name: Fortune Cookie CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Test:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: run-test-step
        run: go test ./frontend
  
  Build-Frontend:
    name: build-frontend-job
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: build docker
        run: ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/frontend/build-docker.sh "frontend"
      - name: push docker
        run: ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && export ENV_NAME="frontend" && ci/push-docker.sh
  
  Build-Backend:
    name: build-backend-job
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: build docker
        run: ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/backend/build-docker.sh
      - name: push docker
        run: ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && export ENV_NAME="backend" && ci/push-docker.sh
