name: Fortune Cookie CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Test:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: run-test-step
        run: go test ./frontend
  
  Build-Frontend:
    name: build-frontend-job
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:GA-${{ github.sha }} 

  Build-Backend:
    name: build-backend-job
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:GA-${{ github.sha }}

  Deploy:
    name: kubernetes-deploy
    runs-on: self-hosted
    needs: [Build-Frontend, Build-Backend]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change frotnend deploy file tags
        run: sed -i "s+{IMG_TAG}+GA-${{ github.sha }}+g" ./kubernetes/deployment-frontend.yaml
      - name: Change backend deploy file tags
        run: sed -i "s+{IMG_TAG}+GA-${{ github.sha }}+g" ./kubernetes/deployment-backend.yaml
      - name: Deploy to Kubernetes
        run: kubectl apply -f ./kubernetes

  Kubernetes-Test:
    name: kubernetes-test
    runs-on: self-hosted
    needs: Deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Curl
        run: bash ./scripts/kubernetes-test.sh
